version: "3.7"
services:

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis:/var/lib/redis
        environment:
            - REDIS_REPLICATION_MODE=master
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
