version: '3'
services:
  db:
    labels:
      - mysql
    restart: "unless-stopped"
    image: mysql:8
    ports:
      - '3306:3306'
    env_file: .env
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - "common"
    healthcheck:
      interval: 10s
      timeout: 20s
      retries: 10

volumes:
  mysql:
    driver: local


networks:
  common: 